---
abstract: 'parity (odd/even/mark/space) handling functions'
author:
  - 'Winfried Koenig'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: String-Parity
requires:
  Exporter: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/String-Parity
  repository: https://github.com/neilbowers/String-Parity.git
version: '1.32'
